<?php

return [
    'ABRA', 
    'AGUSAN DEL NORTE',
    'AGUSAN DEL SUR',
    'AKLAN', 
    'ALBAY', 
    'ANTIQUE', 
    'APAYAO', 
    'AURORA', 
    'BASILAN', 
    'BATAAN', 
    'BATANES', 
    'BATANGAS', 
    'BENGUET', 
    'BILIRAN', 
    'BOHOL', 
    'BUKIDNON', 
    'BULACAN', 
    'CAGAYAN', 
    'CAMARINES NORTE',  
    'CAMARINES SUR',  
    'CAMIGUIN', 
    'CAPIZ', 
    'CATANDUANES', 
    'CAVITE', 
    'CEBU', 
    'COMPOSTELA VALLEY',  
    'DAVAO DEL NORTE',
    'DAVAO DEL SUR',
    'DAVAO OCCIDENTAL',  
    'DAVAO ORIENTAL',  
    'DINAGAT ISLANDS',  
    'EASTERN SAMAR',  
    'GUIMARAS', 
    'IFUGAO', 
    'ILOCOS NORTE',  
    'ILOCOS SUR',  
    'ILOILO', 
    'ISABELA', 
    'KALINGA', 
    'LA UNION',  
    'LAGUNA', 
    'LANAO DEL NORTE',
    'LANAO DEL SUR',
    'LEYTE', 
    'MAGUINDANAO', 
    'MARINDUQUE', 
    'MASBATE', 
    'METRO MANILA',  
    'MISAMIS OCCIDENTAL',  
    'MISAMIS ORIENTAL',  
    'MOUNTAIN PROVINCE',  
    'NEGROS ORIENTAL',  
    'NEGROS OCCIDENTAL',  
    'NORTH COTABATO',  
    'NORTHERN SAMAR',  
    'NUEVA ECIJA',  
    'NUEVA VIZCAYA',  
    'OCCIDENTAL MINDORO',  
    'ORIENTAL MINDORO',  
    'PALAWAN', 
    'PAMPANGA', 
    'PANGASINAN', 
    'QUEZON', 
    'QUIRINO', 
    'RIZAL', 
    'ROMBLON', 
    'SARANGANI', 
    'SIQUIJOR', 
    'SORSOGON', 
    'SOUTH COTABATO',  
    'SOUTHERN LEYTE',  
    'SULTAN KUDARAT',  
    'SULU', 
    'SURIGAO DEL NORTE',
    'SURIGAO DEL SUR',
    'TARLAC', 
    'TAWI TAWI',  
    'WESTERN SAMAR',  
    'ZAMBALES', 
    'ZAMBOANGA DEL NORTE',
    'ZAMBOANGA DEL SUR',
    'ZAMBOANGA SIBUGA',
];